-- Entrepôt analytique (OLAP) - Stripe Business Case
-- Schéma en étoile : une table de faits centrale, sept dimensions dénormalisées,
-- une table de faits d'audit et une table pré-agrégée
-- Aucune donnée personnelle directe (e-mail, adresse IP, jeton) : principe de minimisation (RGPD)

-- Dimensions

CREATE TABLE dim_date (
    date_cle      INT      PRIMARY KEY,
    date_complete DATE     NOT NULL UNIQUE,
    annee         SMALLINT NOT NULL,
    trimestre     SMALLINT NOT NULL CHECK (trimestre BETWEEN 1 AND 4),
    mois          SMALLINT NOT NULL CHECK (mois BETWEEN 1 AND 12),
    nom_mois      TEXT     NOT NULL,
    semaine_iso   SMALLINT NOT NULL CHECK (semaine_iso BETWEEN 1 AND 53),
    jour_mois     SMALLINT NOT NULL CHECK (jour_mois BETWEEN 1 AND 31),
    jour_semaine  SMALLINT NOT NULL CHECK (jour_semaine BETWEEN 1 AND 7),
    nom_jour      TEXT     NOT NULL,
    est_weekend   BOOLEAN  NOT NULL
);

CREATE TABLE dim_client (
    client_cle       INT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id        UUID    NOT NULL UNIQUE,
    code_pays        CHAR(2) NOT NULL,
    nom_pays         TEXT    NOT NULL,
    region           TEXT    NOT NULL,
    date_inscription DATE    NOT NULL
);

CREATE TABLE dim_marchand (
    marchand_cle   INT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marchand_id    UUID    NOT NULL UNIQUE,
    raison_sociale TEXT    NOT NULL,
    categorie      TEXT    NOT NULL,
    code_pays      CHAR(2) NOT NULL,
    nom_pays       TEXT    NOT NULL,
    region         TEXT    NOT NULL
);

CREATE TABLE dim_produit (
    produit_cle             INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produit_id              UUID          UNIQUE,
    nom                     TEXT          NOT NULL,
    prix_catalogue          NUMERIC(12,2),
    code_devise             CHAR(3),
    raison_sociale_marchand TEXT
);

CREATE TABLE dim_geographie (
    geographie_cle INT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_pays      CHAR(2) NOT NULL UNIQUE,
    nom_pays       TEXT    NOT NULL,
    region         TEXT    NOT NULL
);

CREATE TABLE dim_devise (
    devise_cle  INT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_devise CHAR(3) NOT NULL UNIQUE,
    nom         TEXT    NOT NULL
);

CREATE TABLE dim_moyen_paiement (
    moyen_paiement_cle INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type               TEXT NOT NULL,
    marque             TEXT NOT NULL DEFAULT 'non applicable',
    CONSTRAINT uq_type_marque UNIQUE (type, marque)
);

-- Table de faits des transactions : grain = un paiement
-- Partitionnée par mois sur date_cle ; la clé primaire inclut donc la clé de partitionnement

CREATE TABLE fait_transactions (
    transaction_id        UUID          NOT NULL,
    date_cle              INT           NOT NULL REFERENCES dim_date (date_cle),
    client_cle            INT           NOT NULL REFERENCES dim_client (client_cle),
    marchand_cle          INT           NOT NULL REFERENCES dim_marchand (marchand_cle),
    produit_cle           INT           NOT NULL DEFAULT 0 REFERENCES dim_produit (produit_cle),
    geographie_ip_cle     INT           NOT NULL DEFAULT 0 REFERENCES dim_geographie (geographie_cle),
    devise_cle            INT           NOT NULL REFERENCES dim_devise (devise_cle),
    moyen_paiement_cle    INT           NOT NULL REFERENCES dim_moyen_paiement (moyen_paiement_cle),
    heure                 SMALLINT      NOT NULL CHECK (heure BETWEEN 0 AND 23),
    statut                TEXT          NOT NULL,
    type_appareil         TEXT          NOT NULL,
    est_abonnement        BOOLEAN       NOT NULL,
    montant_origine       NUMERIC(12,2) NOT NULL,
    montant_eur           NUMERIC(14,2) NOT NULL,
    montant_rembourse_eur NUMERIC(14,2) NOT NULL DEFAULT 0,
    a_litige              BOOLEAN       NOT NULL DEFAULT false,
    motif_litige          TEXT,
    score_anomalie        NUMERIC(5,4),
    date_chargement       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    PRIMARY KEY (transaction_id, date_cle)
) PARTITION BY RANGE (date_cle);

-- Table de faits d'audit : qui, quoi, quand, sur quelle table (sans valeurs métier)

CREATE TABLE fait_audit (
    audit_id        BIGINT      PRIMARY KEY,
    date_cle        INT         NOT NULL REFERENCES dim_date (date_cle),
    heure           SMALLINT    NOT NULL CHECK (heure BETWEEN 0 AND 23),
    table_cible     TEXT        NOT NULL,
    operation       TEXT        NOT NULL,
    utilisateur_bd  TEXT        NOT NULL,
    date_chargement TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Table pré-agrégée : chiffre d'affaires quotidien par marchand, recalculée pour les jours modifiés

CREATE TABLE agg_ca_quotidien_marchand (
    date_cle              INT           NOT NULL REFERENCES dim_date (date_cle),
    marchand_cle          INT           NOT NULL REFERENCES dim_marchand (marchand_cle),
    nb_transactions       INT           NOT NULL,
    nb_reussies           INT           NOT NULL,
    montant_brut_eur      NUMERIC(16,2) NOT NULL,
    montant_rembourse_eur NUMERIC(16,2) NOT NULL,
    montant_net_eur       NUMERIC(16,2) NOT NULL,
    date_calcul           TIMESTAMPTZ   NOT NULL DEFAULT now(),
    PRIMARY KEY (date_cle, marchand_cle)
);

-- Dictionnaire de données

COMMENT ON TABLE dim_date                  IS 'Calendrier : une ligne par jour, clé au format AAAAMMJJ';
COMMENT ON TABLE dim_client                IS 'Clients sans donnée d''identification directe ; dimension à évolution lente de type 1';
COMMENT ON TABLE dim_marchand              IS 'Marchands avec pays et région dénormalisés';
COMMENT ON TABLE dim_produit               IS 'Produits du catalogue ; clé 0 réservée aux paiements sans produit';
COMMENT ON TABLE dim_geographie            IS 'Pays déduit de l''adresse IP ; clé 0 réservée au pays inconnu';
COMMENT ON TABLE dim_devise                IS 'Devises de paiement';
COMMENT ON TABLE dim_moyen_paiement        IS 'Types et marques de moyens de paiement, sans jeton ni numéro';
COMMENT ON TABLE fait_transactions         IS 'Un paiement par ligne ; montants convertis en euros au taux du jour du paiement';
COMMENT ON TABLE fait_audit                IS 'Actions du journal d''audit de la base transactionnelle, sans valeurs métier';
COMMENT ON TABLE agg_ca_quotidien_marchand IS 'Chiffre d''affaires quotidien pré-agrégé par marchand';

COMMENT ON COLUMN fait_transactions.score_anomalie IS 'Mesure non additive : à utiliser en moyenne ou en seuil, jamais en somme';
COMMENT ON COLUMN fait_transactions.heure          IS 'Heure du paiement en temps universel coordonné (UTC)';
